### ISSUE TITLE
FYI CI wasn't working so I changed the configuration

### ISSUE THREAD

**Issue by tcies** [ethz-asl/minkindr#31]
Previously, the dependency `git@data.asl.ethz.ch:guests/gtsam` was specified in the Jenkins configuration, which resulted in:
```
'gtsam/nonlinear/Expression.h' file not found
```
Thus, I changed the dependency to 
`https://bitbucket.org/gtborg/gtsam.git;fix/moveRawAccess-429-gb66dda2`
which is the same as in https://github.com/ethz-asl/multiagent_mapping

**Comment by tcies** [comment]
`git@bitbucket.org:gtborg/gtsam.git` not `https://bitbucket.org/gtborg/gtsam.git`

**Comment by helenol** [comment]
Can we take a chance to revisit https://github.com/ethz-asl/minkindr/issues/28 and split this repo into minkindr and a separate repo (or whatever uses it) for minkindr_gtsam?
We would like to use minkindr for multirotor stuff, but adding a dep on gtsam makes no sense for us (and look, causes build issues ;) )

**Comment by tcies** [comment]
That sounds good. Who is using minkindr_gtsam?

**Comment by helenol** [comment]
I just looked through 7 pages of ASL repos that I have access to and all the likely offenders (continuous trajectory scanmatching, etc.), but perhaps I just suck at search/package.xml.
I can't find a single dependency on the package.
@mikebosse, @rdube, @gawela, @cfo? Anyone using this or know what it's used for?

**Comment by gawela** [comment]
Yes, @mikebosse @rdube and me are using minkindr_gtsam for curves and it is an essential part of it. It wraps the minkindr type in gtsam Expressions so it can be used with BAD (=Block Automatic Differentiation) in gtsam.

**Comment by gawela** [comment]
Maybe if really noone else uses minkindr_gtsam, it could somehow be bundles with curves?

**Comment by helenol** [comment]
Yeah, that sounds great, and a more appropriate place for it I think. :) Just moving the package to the curves repo as is should work.

**Comment by tcies** [comment]
Finally added multiagent_mapping as a dependency of this and it works. Yes, this is ugly, but it looks like we need a really specific commit, but we can't yet specify branches in continuous integration.

**Comment by HannesSommer** [comment]
But we can specify branches, just as you did with ```git@bitbucket.org:gtborg/gtsam.git;fix/moveRawAccess-429-gb66dda2```. The problem is most likely in fact an authorization problem. 
Why not use ```git@data.asl.ethz.ch:guests/gtsam``` and just update its ```master``` to what we need? That was exactly the reason for why we introduced that repository till we would be able to live with a public branch of gtsam. There we can use our personal credentials. @rdube was used to do that. Is there a new problem with that method?

**Comment by schneith** [comment]
The bitbucket gtsam repo is public since some time. There shouldn't be a problem with credentials anymore.

**Comment by HannesSommer** [comment]
Thanks. So this was a too fast conclusion then. I've think I've got the problem. We do support branch specifications but not a revision specifier like ```fix/moveRawAccess-429-gb66dda2```. This should be rather easy to add and would be an alternative solution.

**Comment by HannesSommer** [comment]
Removed the multiagent_mapping again from the dependencies, because #32 makes it obsolete.

**Comment by HannesSommer** [comment]
Minkindr_gtsam is now using the first dependency specifier https://bitbucket.org/gtborg/gtsam.git;fix/moveRawAccess-429-gb66dda2, which is now supported thanks to https://github.com/ethz-asl/continuous_integration/pull/65.

Good to close?
