### ISSUE TITLE
add .getRotationQuaternion() to minkindr transform?

### ISSUE THREAD

**Issue by helenol** [ethz-asl/minkindr#35]
```
Eigen::Quaterniond q_odom_map = T_odom_map_.getRotation().toImplementation();
```
is a hassle every time you need the rotation component of this transformation, which is all the time.

Any objections to adding a convenience method?

**Comment by schneith** [comment]
Why do you need access to the underlying Eigen type? A convenience function would make sense if you need the coeffs but interacting on the Eigen-type level with the rotation object could bypass some validity checks.

**Comment by helenol** [comment]
We use Eigen rotation types everywhere else in our code (for mav state/waypoints/etc. these are usually decoupled, and some parts plan only the position component and some plan only the yaw).
Is there a better way than using the Eigen type?

**Comment by schneith** [comment]
Ok, I guess then that makes sense.

**Comment by dymczykm** [comment]
@helenol While I agree such convenience method makes sense, do you think the name is actually good? It might be a bit misleading as ``getRotation()`` also returns a quaternion (but a minkindr one). Shouldn't we use Eigen explicitly in the method name?

**Comment by helenol** [comment]
@dymczykm, sure, I agree! getEigenQuaternion()? getEigenRotation()? getRotationEigen()?

**Comment by dymczykm** [comment]
I like getEigenQuaternion best. How about the others?

**Comment by schneith** [comment]
getEigenQuaternion sounds good to me

**Comment by helenol** [comment]
https://github.com/ethz-asl/minkindr/pull/36
