### ISSUE TITLE
Virtual destructors increase size of types by 30%, are they needed?

### ISSUE THREAD

**Issue by cfo** [ethz-asl/minkindr#40]
Currently, with virtual destructors:

sizeof(Quaternion) = 48 bytes
sizeof(Transformation) = 96 bytes

without virtual destructors:

sizeof(Quaternion) = 32 bytes
sizeof(Transformation) = 64 bytes

**Comment by schneith** [comment]
I don't see why they would be needed as long as no one derives from these classes.
Cool, that should save some memory :)

**Comment by schneith** [comment]
Addressed by https://github.com/ethz-asl/minkindr/pull/41

**Comment by cfo** [comment]
great thanks!
