### ISSUE TITLE
Support vectorized transformations/rotations

### ISSUE THREAD

**Issue by furgalep** [ethz-asl/minkindr#5]
Something like:
```c++
Eigen::Matrix<double, 3, Eigen::Dynamic> W_landmarks;
Transformation T_B_W;
// ... fill in.

Eigen::Matrix<double, 3, Eigen::Dynamic> B_landmarks(T_B_W.transform(W_landmarks));
```

**Comment by tcies** [comment]
Will do :)

**Comment by tcies** [comment]
Only for non-homogeneous, if ok, I don't have the means to verify homogeneous.

**Comment by tcies** [comment]
The next radical thing would be a QuatTransformations type which has a Matrix3X for positions and a vectorized quaternion form (wait, does that exist?) for rotations, so we can mass-transform transformations. Not that it couldn't be useful (batch-transforming missions into the global frame). :)

**Comment by simonlynen** [comment]
@tcies I don't think there is a use-case for transforming multiple transformations at once.

**Comment by dymczykm** [comment]
@simonlynen How about transforming store landmark ids to global coordinates when streaming to the agent?

**Comment by simonlynen** [comment]
Yes, but I don't see how transforming multiple _transformations_ in batch help here.
