### ISSUE TITLE
Schweizer Messer Dependency

### ISSUE THREAD

**Issue by alexmillane** [ethz-asl/minkindr#67]
This seems like a fairly heavy dependency to me, especially since the vast majority of people (I assume) are using this as a C++ library only.

Any opinions?

**Comment by HannesSommer** [comment]
Where do you find a dependency on SchweizerMesser? That would be an accident. To avoid that we actually extracted numpy_eigen and the python module support code from SchweizerMesser (if I remember right). Also, you don't have the above dependencies in the cpp package only in the python package. Do you build the entire workspace? In that case I would recommend against that in general. If you have to you could add a CATKIN_IGNORE. If that is too much we can of course consider splitting the repo, but that has also some disadvantages.

**Comment by alexmillane** [comment]
Apologies, I hadn't seen that you separated numpy_eigen from SchweizerMessser.

We (ASL MAV team) are almost always building the entire workspace, at least on a new install. We 50-100 packages in our stack, installed on many platforms, most of which are actually needed, so individually building packages isn't really an option. Obviously having some failing packages isn't really a problem though.

That said, given our liberal approach to separating packages, we separate the ROS interface to minkindr [minkindr_ros](https://github.com/ethz-asl/minkindr_ros) for example, this strikes me an odd pair to keep together. But perhaps my use is atypical though.

**Comment by alexmillane** [comment]
Anyway, we just added the required to deps to our standard install scripts, so no worries. Just wanted to avoid adding SchweizerMesser. Cheers :+1:
